name: Daily Exchange Rate Scraper

on:
  schedule:
    # Runs every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    
    # CRITICAL: Prevent concurrent runs
    concurrency:
      group: exchange-rate-scraper
      cancel-in-progress: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas selenium webdriver-manager

      - name: Run the scraper
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
        run: python exchange_rate_scraper.py

      - name: Fetch latest changes
        run: |
          git fetch origin main
          git rebase origin/main

      - name: Commit and push updated CSV
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add western_union_rates.csv
          git commit -m "Update CSV with new exchange rates" || echo "No changes to commit"
          git push