name: Daily Exchange Rate Scraper

on:
  schedule:
    # Runs every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    
    # Prevent concurrent runs to avoid conflicts
    concurrency:
      group: exchange-rate-scraper
      cancel-in-progress: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas selenium webdriver-manager

      - name: Run the scraper
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
        run: python exchange_rate_scraper.py

      - name: Commit and push if changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update CSV with new exchange rates'
          file_pattern: western_union_rates.csv
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>